### ISSUE TITLE
Not very customizable

### ISSUE THREAD

**Issue by ruskid** [Detaysoft/react-chat-elements#102]
For instance, Avatars expects URL strings, not possible to render custom components for ChatItem.

I would like to generate the avatar using initials.

Also impossible to render a custom typed message. Which can be easily added.

**Comment by abdurrahmanekr** [comment]
You're right about the avatar. But you can customize the messages as you like. Because you can rewrite rce's styles (such as Theme).

For example:
```javascript
<MessageBox
    position='left'
    type='text'
    text={(
        <div>
            <h4>Title</h4>
            <p>Lorem ipsum dolor sit amet...</p>
        </div>
    )}
    />
```
You can create and use a style file such as rce-my-template.css.

Making this project customizable is something the community has in hand.

We designed this project for our own application and made it open source. We have a messaging application and most people don't have design-related requests. And about 400 people use this app.

Because we are using a template instead of changing this project. But it's good to do customizable things.

It seems difficult for us to allocate resources for this. We expect the community to add customizable features.

Thanks for your comment.

**Comment by ruskid** [comment]
I completely understand your point and I forgot to say thanks for making it available to the public!

It's just a comment for people, I will try to contribute later if I can. Your project works great for prototyping!
