### ISSUE TITLE
toBottomHeight={'100%'} does not work

### ISSUE THREAD

**Issue by Magdo-glitch** [Detaysoft/react-chat-elements#111]
Hello, 

when I render the MessageList it does not position itself to the bottom. 
Same thing when I write a new message. 

Thanks for the support

**Comment by abdurrahmanekr** [comment]
Hello, This line doesn't work in a way I don't understand.
https://github.com/Detaysoft/react-chat-elements/blob/5334dd3a9828ccaf0e618295331c7e2c23b3dda8/src/MessageList/MessageList.js#L41

Can you try it? Why is this happening?

**Comment by Magdo-glitch** [comment]
[Chat-test.zip](https://github.com/Detaysoft/react-chat-elements/files/4098261/Chat-test.zip)

This is a piece of my project, enjoy

**Comment by geiszla** [comment]
I had the same problem, because initially, the `MessageList` got the full message list as data source, and so it didn't change, therefore it didn't scroll to the bottom. I needed to add a callback to scroll it after the component mounted.

```ts
const messageListElement = React.useCallback((node) => {
    if (node !== null) {
      if (node && node.mlistRef) {
        node.setState({ scrollBottom: node.getBottom(node.mlistRef) }, node.checkScroll.bind(node));
      }
    }
  }, []);

...

return (
    <Messages
      ref={messageListElement}
      lockable
      dataSource={messages}
      toBottomHeight="100%"
    />
);
```

If would be good though if there was an option to scroll down to the bottom initially without changing the data source.

**Comment by i-mighty** [comment]
@geiszla solution doesn't seem to work for me though.

**Comment by geiszla** [comment]
@i-mighty Can you give a bit more info? Does it not call the callback, or can it not get the bottom, or what exactly the problem is? I still use this exact code in my app and it works just fine.

Also, check if the scroll bar is on the right element. It may be that the bar is not on the message list, but on one of the ancestors and so you can scroll it, but the code above will not work.

**Comment by nicksome168** [comment]
encountered the same issue :(
messageList didn't scroll down as datasource updated

**Comment by marciok** [comment]
Make sure to add a class with height and overflow auto, ex: 

```css
/* index.css */
.my-chat {
  height: 800px;
  overflow: auto;
}
```
```js
    <MessageList
      ref={messageListElement}
      lockable
      className="my-chat" # <- Add your class
      dataSource={messages}
      toBottomHeight="100%"
    />
```
