### ISSUE TITLE
Overflow of message content on small screens

### ISSUE THREAD

**Issue by aliogaili** [Detaysoft/react-chat-elements#38]
Due to hardcoded widths, some message content width is exceeding the width of the container on small screens.

**rce-mbox-location**
<img width="237" alt="screen shot 2017-10-22 at 3 10 28 pm" src="https://user-images.githubusercontent.com/1675307/31861265-3e72073a-b73b-11e7-9130-5d73df1d887b.png">

**rce-mbox-photo--img**
<img width="270" alt="screen shot 2017-10-22 at 3 12 32 pm" src="https://user-images.githubusercontent.com/1675307/31861280-7a250e4e-b73b-11e7-9b35-71eab57e599a.png">

This could also has to do with the way I'm managing the parent container width.

Let me know if anyone can replicate this, thank you.

**Comment by mlelyakan** [comment]
@aliogaili We're faced with the same issue in our project. The problem is caused by the messagebox component. We're going to solve this as soon as possible. 
Which version are you using ?
Thanks for the reporting.

**Comment by abdurrahmanekr** [comment]
The best way to solve that issue is removing **max-width**.
https://github.com/Detaysoft/react-chat-elements/blob/b823d3839477111738615cbabaeb8d09d206e203/src/MessageBox/MessageBox.css#L65
@aliogaili what do you think about this solution? Would be a good solution for you? Feel free to submit a PR if @aliogaili or anyone else wants to submit a fix for this.

**Comment by abdurrahmanekr** [comment]
That issue fixed on #37

**Comment by aliogaili** [comment]
I'm using version 0.5.2. I noticed that if I removed the style width (300px) in the rce-mbox-photo--img, then the image position correctly.
